### ISSUE TITLE
请更新下文档  

### ISSUE THREAD

**Issue by PERSISTENC** [alibaba/ChatUI#10]
谢谢

**Comment by PERSISTENC** [comment]
文档的版本 是不是和实际展示案例 是不是差距蛮大 好多都没有写

**Comment by PERSISTENC** [comment]
是sdk 的文档 如 chat 容器里面消息是如何排序 是按时间来么 ？哪个历史消息 如何就排到前面了 ？*-*

**Comment by akai** [comment]
> 是sdk 的文档 如 chat 容器里面消息是如何排序 是按时间来么 ？哪个历史消息 如何就排到前面了 ？_-_

和钉钉、微信等 IM 一样的逻辑啊，发送的先后顺序，上旧下新，所以历史消息在最上面

**Comment by PERSISTENC** [comment]
那个历史消息哦 我一开始看文档猜  我以为是按照时间得 结果不对 后来 再猜是直接返回个数组 也不对 最后就是死马当做活马医 返回一个带list得结构 没成想对了  （我一开始看到那个接口定义 我压根以为那就是消息得数据结构定义，根本就没想到 需要返回一个object 里面包含list  ）

**Comment by akai** [comment]
文档下面是有用 ts 写了数据结构，再下面还有示例

**Comment by PERSISTENC** [comment]
> 文档下面是有用 ts 写了数据结构，再下面还有示例

我们这个重构的  不牵扯到后端 所以数据格式不怎么好改 要么就是起中间层 自己转  我采用的是history 里面处理数据 所以我一开始是按照你们这数据结构 直接appendMessag的 所以才有疑问 是按照时间排的么  后来慢慢的摸索 才搞好

**Comment by PERSISTENC** [comment]
> 文档下面是有用 ts 写了数据结构，再下面还有示例

谢谢您
