### ISSUE TITLE
如何删除chatbot里面的scrollbar?

### ISSUE THREAD

**Issue by komo-ai** [alibaba/ChatUI#105]
**What problem does this feature solve? (这个功能解决了什么问题)**
chatbot UI里面的滚动条非常影响UI的美观，有没有方法可以删除？

尝试了
```
::-webkit-scrollbar {
  display: none;
}
```
但是完全没有变化。

另外用户群的QRcode已经过期了。

**Comment by akai** [comment]
你可以网上搜下解决方案
