### ISSUE TITLE
可以提供beforeunload事件的功能吗

### ISSUE THREAD

**Issue by 82kg** [alibaba/ChatUI#106]
**What problem does this feature solve? (这个功能解决了什么问题)**

假如还不想退出聊天。误点了关闭tab，可以给出提醒

**Describe the solution you'd like (描述您想要的解决方案)**

封装一个component

**What does the proposed API look like?  (你期望的 API 是怎样的)**

pro版本的话，可以在new ChatSDK增加一个 监听

**Comment by akai** [comment]
你直接监听这个事件就好了吧，感觉没必要封装进来
