### ISSUE TITLE
表情功能

### ISSUE THREAD

**Issue by xiaodoubaoldl** [alibaba/ChatUI#110]
**What problem does this feature solve? (这个功能解决了什么问题)**
表情、图片功能
**Describe the solution you'd like (描述您想要的解决方案)**
demo
通过demo可以看到表情、图片等更多功能的代码实现
**What does the proposed API look like?  (你期望的 API 是怎样的)**
demo
通过demo可以看到表情、图片等更多功能的代码实现
<img width="360" alt="image" src="https://github.com/alibaba/ChatUI/assets/25196057/a06184cf-1bb0-40f4-be2a-bb490e2029f7">

**Comment by wblovezqy** [comment]
项目停了吧，我也没找到这个功能怎么用接口实现，官网的demo是有表情的

**Comment by xiaodoubaoldl** [comment]
> 项目停了吧，我也没找到这个功能怎么用接口实现，官网的demo是有表情的

`{
            type: 'smile',
            icon: 'smile',
            title: '表情',
            render: () => <div style={{height: "87px",overflow: "scroll",display: "flex", justifyContent:"center"}}><Picker i18n={myi18n} previewPosition="none" perLine={10} searchPosition="none" navPosition="none" data={data} onEmojiSelect={(val)=>handleSend("text", val.native)} /></div>
            // render: () => <div style={{height: "87px",overflow: "scroll"}}>
            //     <Emoji onEmojiSelect={(val)=>handleSend("text", val.native)}/>
            // </div>
        },`
