### ISSUE TITLE
不能通过改变Chat对话容器的inputType值切换输入框<=>语音输入框

### ISSUE THREAD

**Issue by shangdev** [alibaba/ChatUI#112]
![image](https://github.com/alibaba/ChatUI/assets/15621520/53b2a95d-49cc-47a6-a9ee-7960d2a4269f)

如何通过传递是voice还是text切换输入框类型，难道这个 inputType 只是个默认值吗？

**Comment by akai** [comment]
`inputType="voice"` 不行吗？

**Comment by shangdev** [comment]
@akai 初始化时指定 inputType="voice" 或 inputType="text" 是有效的，但是如果将一个 state 赋值给 inputType，然后通过 setState 设置时无效

**Comment by akai** [comment]
是的，只在初始化生效，后续就通过图标来切换就好了

**Comment by shangdev** [comment]
@akai 最好还是可以通过变量来切换.。使用场景：语音权限不可用时，切换会文本输入。

**Comment by akai** [comment]
> @akai 最好还是可以通过变量来切换.。使用场景：语音权限不可用时，切换会文本输入。

你这个场景可以在初始化的时候就确认 inputType
