### ISSUE TITLE
请问在react 脚手架（chatui sdk）中使用chatui 的本地组件 会出现react版本错误的问题么？

### ISSUE THREAD

**Issue by PERSISTENC** [alibaba/ChatUI#12]
![image](https://user-images.githubusercontent.com/24719856/102869177-3327ad00-4476-11eb-84f4-5ab7ebae1e98.png)

**Comment by akai** [comment]
ChatUI Pro (SDK) 自带了 React，你本地的组件可以用全局的 React、ReactDOM

**Comment by minbinHuang** [comment]
请问如何使用本地的react版本
