### ISSUE TITLE
typescript Tab类型检查出错

### ISSUE THREAD

**Issue by CaffeiiX** [alibaba/ChatUI#120]
**Version information (版本信息)**
- ChatUI
- ChatUI Version: 2.4.2
- React Version: 18
- OS Version: windows7
- Browser Version: chrome103

**Describe the bug (描述问题)**
typescript 编译环境下，引入Tab以及Tabs组件，ts类型检查报错， tabprops不存在children属性
**Steps To Reproduce (重现步骤)**
1. ts环境下
2. 输入 <Tabs><Tab></Tab></Tabs>

**Expected behavior (期望的结果是什么)**
@ts no-check下编译通过，期望tabpros类型声明存在children属性

**Comment by pcyanglei** [comment]
yarn upgrade @chatui/core@^2.5.5-beta.0

**Comment by CaffeiiX** [comment]
> yarn upgrade @chatui/core@^2.5.5-beta.0

Thank You

**Comment by supuwoerc** [comment]
> yarn upgrade @chatui/core@^2.5.5-beta.0

升级完useMessages里面的setTyping没了...没向下兼容吗=。=
