### ISSUE TITLE
由于项目框架老旧，使用hooks写法打包报错。

### ISSUE THREAD

**Issue by xiaodoubaoldl** [alibaba/ChatUI#123]
**What problem does this feature solve? (这个功能解决了什么问题)**

**Describe the solution you'd like (描述您想要的解决方案)**

****有没有类组件写法的版本及使用文档？

**What does the proposed API look like?  (你期望的 API 是怎样的)**

**Comment by olivershen-wow** [comment]
同问

**Comment by akai** [comment]
升级 react 吧
