### ISSUE TITLE
小程序开发如何使用

### ISSUE THREAD

**Issue by niu-dali** [alibaba/ChatUI#124]
**What problem does this feature solve? (这个功能解决了什么问题)**

在小程序开发项目中使用

**Describe the solution you'd like (描述您想要的解决方案)**

现在都是多端统一开发了，居然还是只有web前端的组件，能不能出个flutter、vue、react、小程序端的组件

**What does the proposed API look like?  (你期望的 API 是怎样的)**

**Comment by Thinking80s** [comment]
同问+1

**Comment by Lynne42** [comment]
有解决吗， 能在小程序中使用吗

**Comment by akai** [comment]
ChatUI暂时没有小程序版本，可以试试用小程序的 `web-view` 来打开 H5 页面
