### ISSUE TITLE
如何禁用 Input Box

### ISSUE THREAD

**Issue by songbohu** [alibaba/ChatUI#127]
**What problem does this feature solve? (这个功能解决了什么问题)**

我希望可以选择性的去禁用对话容器中的input box。

**Describe the solution you'd like (描述您想要的解决方案)**

支持html中的disabled attribute。

**What does the proposed API look like?  (你期望的 API 是怎样的)**

```
<Chat
  disabled={true}
/>
```

谢谢

**Comment by akai** [comment]
传 inputOptions：

```jsx
  return (
    <Chat
      inputOptions={{ disabled: true }}
    />
  );
```
