### ISSUE TITLE
SSE流式响应处理

### ISSUE THREAD

**Issue by Malebazi** [alibaba/ChatUI#139]
![image](https://github.com/alibaba/ChatUI/assets/88440262/9958bd1d-7d64-4cda-8c01-9f308fa9a33c)

代码注释中有这样一句话：“当需要增加header或者websocket、sse等特殊形式消息处理时，可以返回Promise，假如返回Promise对象是空对象，则不会展示消息内容”，然而文档中并没有对应描述。

由于没法加群，只能在issue里提了。。。有大佬知道怎么上SSE嘛？

**Comment by Malebazi** [comment]
搞定。希望文档能更完善。

**Comment by BoBoooooo** [comment]
> 搞定。希望文档能更完善。

遇到同样的问题了，请教下

**Comment by Malebazi** [comment]
chatui pro的promise里面用微软azure的fetch-sercer-events项目（应该是叫这个）



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月29日 17:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [alibaba/ChatUI] SSE流式响应处理 (Issue #139) |

搞定。希望文档能更完善。

遇到同样的问题了，请教下

**Comment by Malebazi** [comment]
https://github.com/Azure/fetch-event-source 这个



在 2024-04-29 17:41:09，"BoBoooooo" ***@***.***> 写道：

搞定。希望文档能更完善。

遇到同样的问题了，请教下

**Comment by Malebazi** [comment]
![image](https://github.com/alibaba/ChatUI/assets/88440262/da8318e0-c8ed-43c0-9f6f-4fa565d3956c)
大概这样
