### ISSUE TITLE
icon图标用不了

### ISSUE THREAD

**Issue by liyanping111** [alibaba/ChatUI#141]
**Version information (版本信息)**
- ChatUI or ChatUI Pro?   chatUI
- ChatUI Version:   2.4.2
- React Version:   16.12.0
- OS Version:
- Browser Version:

**Describe the bug (描述问题)**
ICON图表用不了
**Steps To Reproduce (重现步骤)**
1. 
![icon](https://github.com/alibaba/ChatUI/assets/27598896/96306bb2-f24a-486f-8175-6e0fabaa7d48)
明明写着是2.4.3可为什么我指定版本下载2.4.3说是没有该版本呢

2. 
![icon1](https://github.com/alibaba/ChatUI/assets/27598896/47c6c925-7fd5-4d65-a8d8-29f5d7b4bd74)

**Link to minimal reproduction (最小化重现链接)**

**Expected behavior (期望的结果是什么)**
icon图标可以使用中的copy使用不了

**Comment by akai** [comment]
图标库是用的单独的 cdn js，你可以引用 `//g.alicdn.com/chatui/icons/2.0.1/index.js` 及以上版本就有了
