### ISSUE TITLE
如何在input中使用类似antd中的Mentions 提及的功能

### ISSUE THREAD

**Issue by tlbb764652810** [alibaba/ChatUI#146]
**What problem does this feature solve? (这个功能解决了什么问题)**
在输入信息中想要@某个人的功能
**Describe the solution you'd like (描述您想要的解决方案)**
可以支持@某个人，实现类似antd中的Mentions 提及
**What does the proposed API look like?  (你期望的 API 是怎样的)**
在Chat 对话容器可以添加类似的配置实现这个功能

**Comment by akai** [comment]
暂时没有哦，但你自己实现起来也不难的，监听一下输入的内容，渲染list，点击后更新输入内容
