### ISSUE TITLE
关于setState不能及时获取最新值

### ISSUE THREAD

**Issue by liuhailang** [alibaba/ChatUI#15]
这里的currentSlide !== this.state.currentSlide永远不会成立
const { currentSlide } = this.state;

    this.setState({
      currentSlide: Math.min(Math.max(index, 0), this.len - 1),
    });

    // eslint-disable-next-line react/destructuring-assignment
    if (currentSlide !== this.state.currentSlide) {
      this.slideToCurrent();
      onChange.call(this);
      if (callback) {
        callback.call(this);
      }
    }

**Comment by akai** [comment]
Carousel 组件已经用 hooks 重构了，你说的问题已不存在
