### ISSUE TITLE
ChatSDK foundation-model 大模型卡片 渲染 html代码的问题

### ISSUE THREAD

**Issue by dantethr** [alibaba/ChatUI#153]
**Version information (版本信息)**
- ChatUI or ChatUI Pro? ChatSDK
- ChatUI Version: ChatSDK 6.4.5
- React Version:
- OS Version:
- Browser Version:

**Describe the bug (描述问题)**
foundation-model 大模型卡片 不能正确渲染 html代码。markdown卡片没有问题。
**Steps To Reproduce (重现步骤)**
1. 
<img width="512" alt="微信图片_20241213115016" src="https://github.com/user-attachments/assets/d84e9396-88f7-4817-8e9a-64009b19b6d4" />

2.
<img width="460" alt="微信图片_20241213115046" src="https://github.com/user-attachments/assets/4664a867-1583-4efd-acc3-de0b1f394808" />
如图所示

**Comment by laomu1988** [comment]
因为通义晓蜜大模型会返回配置的富文本，所以大模型卡片使用会判断是否包含</div>，包含</div>就使用html渲染模式进行渲染，假如纯markdown渲染建议使用markdown卡片
