### ISSUE TITLE
ticket card is not work

### ISSUE THREAD

**Issue by 402210313** [alibaba/ChatUI#18]
https://g.alicdn.com/alime-components/ticket/0.0.2/index.js
 {
                    type: 'card',
                    content: {
                        code: "ticket",
                        data: {
                            "transportInfo": {
                                "to": "北京",
                                "icon": "train",
                                "searchLinkName": "更多车次",
                                "weekday": "周六",
                                "from": "杭州",
                                "date": "2017-12-16",
                                "searchLink": "https://h5.m.taobao.com/trip/train/searchlist/index.html?depCity=杭州&arrCity=北京&depDate=2017-12-16&onlyGD=false&ttid=taobao.xiaomi.huoqi.104666"
                            },
                            "transportList": [{
                                "bestPrice": 538.5,
                                "spendTime": "5小时55分",
                                "bestDiscount": "",
                                "departName": "杭州东",
                                "orderLink": "https://h5.m.taobao.com/trip/train/train-detail/index.html?depStation=杭州东&arrStation=北京南&depDate=2017-12-16&trainNo=G34&isStudent=0&ttid=taobao.xiaomi.huoqi.104666&spm=181.7406757.1998410225.500&_preProjVer=0.5.55&_projVer=0.5.55",
                                "ontimeRate": "",
                                "transportName": "G34",
                                "otherFlight": "",
                                "leftNum": "商务座 20张 一等座 有票 二等座 有票",
                                "arriveName": "北京南",
                                "depTime": "07:10",
                                "arrTime": "13:05"
                            }, {
                                "bestPrice": 538.5,
                                "spendTime": "5小时14分",
                                "bestDiscount": "",
                                "departName": "杭州东",
                                "orderLink": "https://h5.m.taobao.com/trip/train/train-detail/index.html?depStation=杭州东&arrStation=北京南&depDate=2017-12-16&trainNo=G20&isStudent=0&ttid=taobao.xiaomi.huoqi.104666&spm=181.7406757.1998410225.500&_preProjVer=0.5.55&_projVer=0.5.55",
                                "ontimeRate": "",
                                "transportName": "G20",
                                "otherFlight": "",
                                "leftNum": "商务座 1张 一等座 有票 二等座 有票",
                                "arriveName": "北京南",
                                "depTime": "08:24",
                                "arrTime": "13:38"
                            }]
                        }
                    }
                }

**Comment by akai** [comment]
你用的是小蜜？这卡片渲染逻辑不是写在 ChatUI 里的。
