### ISSUE TITLE
文档中的效果图无法显示

### ISSUE THREAD

**Issue by tourze** [alibaba/ChatUI#19]
![image](https://user-images.githubusercontent.com/13899502/106703539-5f158100-6625-11eb-8126-63ec77624129.png)

随便找个图片路径 https://intranetproxy.alipay.com/skylark/lark/0/2020/png/83084/1584339068897-147dd4dd-aa5f-4d12-ba71-57ffbca0ec77.png ，应该是使用了ali内部的地址吧

**Comment by akai** [comment]
这边用4G网测试过是可以访问的

**Comment by tourze** [comment]
好诡异喔。在电脑上的确无法访问图片，手机可以。

**Comment by akai** [comment]
已更新图片CDN地址
