### ISSUE TITLE
样式文件与antd有冲突

### ISSUE THREAD

**Issue by DerekHQ** [alibaba/ChatUI#20]

**Comment by akai** [comment]
ChatUI 目前是有全局样式的，还有输入框定位的处理，建议你用 iframe 或沙盒机制

**Comment by akai** [comment]
我们将要升级到新的 UI，到时会解决次问题

**Comment by zqjimlove** [comment]
> 我们将要升级到新的 UI，到时会解决次问题
@akai 

大概什么时候能放出升级？或者后续能兼容旧版的UI吗？最近在调研，想使用 ChatUI

**Comment by qivhou** [comment]
有更新？

**Comment by Gagoooooo** [comment]
有更新？
