### ISSUE TITLE
chat容器组件在iOS 12.4.9 九宫格拼音输入法下：出现调起输入法后点击发送按钮无反应问题

### ISSUE THREAD

**Issue by kevin-zeus** [alibaba/ChatUI#23]
用到的组件：chat对话容器

系统：iOS 12.4.9
浏览器：WKWebview内打开chat对话容器的Demo

问题：使用拼音九宫格输入法输入内容，会出现点击发送按钮或空白区域，键盘不收回，发送按钮未响应

尝试过程：在拼音九宫格输入法情况下，使用Safari打开Demo正常；在WKWebview内使用Input组件正常，但是chat容器的输入框会有问题；

**Comment by akai** [comment]
诶遇到过你说的现象，有视频和 DEMO 吗
