### ISSUE TITLE
如果可以的话，想要关于hooks的更详细的文档，比如useMessages当中的initialState具体能写什么。

### ISSUE THREAD

**Issue by honeysuckcle** [alibaba/ChatUI#27]
**What problem does this feature solve?**

**Describe the solution you'd like**

**What does the proposed API look like?**

**Comment by akai** [comment]
https://github.com/alibaba/ChatUI/blob/bab628a165d39bb0a69a0ef26d0abc4f0cef1789/src/components/Message/Message.tsx#L14-L47
