### ISSUE TITLE
请问能出个自定义卡片的模板吗

### ISSUE THREAD

**Issue by lun324** [alibaba/ChatUI#28]
**What problem does this feature solve?**

**Describe the solution you'd like**

**What does the proposed API look like?**

**Comment by akai** [comment]
参考文档 https://chatui.io/sdk/custom-component

**Comment by xie-rgb** [comment]
说实话我第一次用自定义卡片也不知道怎么使用 。官网只写怎么引， 不说明怎么使用...   到现在有的人也一脸懵。 引过来的卡片。不知道什么时候让其展示出来...  官网需要在当前页面 展示一个例子 https://chatui.io/sdk/custom-component

**Comment by 82kg** [comment]
> 说实话我第一次用自定义卡片也不知道怎么使用 。官网只写怎么引， 不说明怎么使用... 到现在有的人也一脸懵。 引过来的卡片。不知道什么时候让其展示出来... 官网需要在当前页面 展示一个例子 https://chatui.io/sdk/custom-component

官方一脸不屑

**Comment by BugApe** [comment]
> 说实话我第一次用自定义卡片也不知道怎么使用 。官网只写怎么引， 不说明怎么使用... 到现在有的人也一脸懵。 引过来的卡片。不知道什么时候让其展示出来... 官网需要在当前页面 展示一个例子 https://chatui.io/sdk/custom-component

您好，同样的困惑，能简单写个例子吗，在component中注册了以后，content里怎么配置呢
