### ISSUE TITLE
chatui是如何解决输入框会键盘挡住的问题呢?

### ISSUE THREAD

**Issue by sin911** [alibaba/ChatUI#3]
大佬们,我在公众号上看到chatUI的介绍,其中有一句是**解决输入框定位：出软键盘后，输入框会被键盘挡住的问题**
具体是怎么解决的呢?谢谢大佬

**Comment by akai** [comment]
具体可查看 https://github.com/alibaba/ChatUI/blob/master/src/components/Composer/riseInput.ts，但某些情况还需要 App 配合调整 https://chatui.io/sdk/faq

**Comment by sin911** [comment]
多谢大佬指点没,另外https://chatui.io/sdk/faq网址里的**### [Android 爬坑之旅：软键盘挡住输入框问题的终极解决方案]**
404了

**Comment by akai** [comment]
也可以搜一下这个标题，网上有不少方案的
