### ISSUE TITLE
maxLength

### ISSUE THREAD

**Issue by MarcM0** [alibaba/ChatUI#36]
**What problem does this feature solve? (这个功能解决了什么问题)**
At the moment you can enter any amount of items in the chat input box

**Describe the solution you'd like (描述您想要的解决方案)**
a parameter for the chat item with a max input length
https://chatui.io/components/chat

**Comment by akai** [comment]
This feature has been added in the `next` branch，see https://github.com/alibaba/ChatUI/commit/3743eaf3f6f3a5764bb7d790397a19ea7af85d0c

for example:
```js
<Chat inputOptions={{ maxLength: 104, showCount: false }} />
```

**Comment by MarcM0** [comment]
Thank you, do you know when I'll be able to update to this branch?

**Comment by akai** [comment]
You can use the beta version first `1.0.0-beta.4`. And the official version will be released soon.
