### ISSUE TITLE
需求：根据消息ID，定位到某一个消息的位置。 模仿查看历史消息，点击定位到消息所在位置。

### ISSUE THREAD

**Issue by xie-rgb** [alibaba/ChatUI#37]
此功能可以解决什么问题？（这个功能解决了什么问题）
通过消息id或其他方式定位到聊天框内消息所在位置，最好有一个选中状态

描述您想要的解决方案？（描述您想要的解决方案）
给出一方法，传值定位消息列表到消息所在位置

拟议的API是什么样的？（您期望的API是怎样的）
怎么方便怎么来，无要求

**Comment by akai** [comment]
请问你具体的场景是怎么样的？

**Comment by xie-rgb** [comment]
> 可以说一下你具体的场景吗
我有个查询历史消息功能 ，搜索到历史的消息，然后点击查到的消息就 在聊天框显示到相应的位置。   场景和微信，qq，钉钉的查看历史一样。你可以点一下     简单的消息定位。

**Comment by akai** [comment]
ChatUI v1.0 可以这样：

```js
document.querySelector(`.Message[data-id=${msgId}]`).scrollIntoView()
```
