### ISSUE TITLE
Toast Duration

### ISSUE THREAD

**Issue by MarcM0** [alibaba/ChatUI#38]
**What problem does this feature solve? (这个功能解决了什么问题)**
Toast notifications go too fast

**Describe the solution you'd like (描述您想要的解决方案)**
Some argument to control toast durations (or even an option to stay permanently)

**What does the proposed API look like?  (你期望的 API 是怎样的)**
toast.fail("Error: Help",30000);

https://chatui.io/components/toast

**Comment by akai** [comment]
Yes, you can use it like this
```js
fail(content: string, duration?: number)
```
