### ISSUE TITLE
Timestamps not in english

### ISSUE THREAD

**Issue by MarcM0** [alibaba/ChatUI#39]
**Version information (版本信息)**
- ChatUI or ChatUI Pro? ChatUI
- ChatUI Version: 0.3.3
- React Version: 17.0.2
- OS Version: Windows 10
- Browser Version: Chrome (latest)

**Describe the bug (描述问题)**
In the dates shown in chat, the dates are not displayed in english, instead of "yesterday" it says "昨天"

**Steps To Reproduce (重现步骤)**
1. create a message with a timestamp that is a different day (or leave a chat running for a day)

**Comment by akai** [comment]
```jsx
<Chat locale="en-US" />
```

**Comment by MarcM0** [comment]
thank you, although just a heads up the documentation says its english by default

**Comment by Me2ll** [comment]
@akai  Hello, I'm am using chatUI. Is there "tr-TR" language support?
