### ISSUE TITLE
官网中的demo显示请求无响应，开启或关闭我的梯子都不能访问，请问是内部的网站吗？

### ISSUE THREAD

**Issue by dumplings** [alibaba/ChatUI#4]
显示的内容是 `market.wapa.taobao.com 的响应时间过长。`，我ping了一下，显示hosts错误，请问这是阿里内部的网站吗？

![image](https://user-images.githubusercontent.com/16367785/94640585-b91dd700-0311-11eb-9083-f76c905217d2.png)

![image](https://user-images.githubusercontent.com/16367785/94640600-c1761200-0311-11eb-958c-ef23af763605.png)

**Comment by CarberryChai** [comment]
一样一样的，上来issue看一下，果然有人提问了，这么明显的错误不应该呀……

**Comment by akai** [comment]
不好意思，demo 的环境判断出了问题，问题已修复需节后发布上线，大家可以暂时先用 https://chatui.alimebot.com/components/button 来访问，给大家添加麻烦了

**Comment by akai** [comment]
已修复
