### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by MarcM0** [alibaba/ChatUI#40]
**What problem does this feature solve? (这个功能解决了什么问题)**
In 0.3.3, the text on the primary type button is white. but on the latest beta, it's black and there is no where you can change it unless you set gray-1=white or something

**Describe the solution you'd like (描述您想要的解决方案)**
some option to change the text colour on the buttons

**Comment by MarcM0** [comment]
Now that I think about it, I'm not sure this UI change was intentional, 
![image](https://user-images.githubusercontent.com/30278842/121083094-00b40700-c7ad-11eb-92ab-23480e82c742.png)
It seems than index has a syntax error

**Comment by akai** [comment]
Yes, the beta version has a new UI. If you want to change the style, you can use the less variable. see https://chatui.io/docs/customize-theme

**Comment by akai** [comment]
> Now that I think about it, I'm not sure this UI change was intentional,
> ![image](https://user-images.githubusercontent.com/30278842/121083180-188b8b00-c7ad-11eb-8cae-09fd395de599.png)
> It seems than index.css has a syntax error (I get this message when I run "npm run build")

Which version is this?

**Comment by MarcM0** [comment]
> Yes, the beta version has a new UI. If you want to change the style, you can use the less variable. see https://chatui.io/docs/customize-theme

Yes but the problem is, the text on primary buttons is gray-1 which means that for any darker brand colour, I would have to set gray-1 = #fff for the buttons to be legible

**Comment by MarcM0** [comment]
> > Now that I think about it, I'm not sure this UI change was intentional,
> > ![image](https://user-images.githubusercontent.com/30278842/121083180-188b8b00-c7ad-11eb-8cae-09fd395de599.png)
> > It seems than index.css has a syntax error (I get this message when I run "npm run build")
> 
> Which version is this?

I've tried both 1.0.0-beta.5 and 1.0.0-beta.4 and it happened on both. I have not tried the other betas

**Comment by akai** [comment]
> > Yes, the beta version has a new UI. If you want to change the style, you can use the less variable. see https://chatui.io/docs/customize-theme
> 
> Yes but the problem is, the text on primary buttons is gray-1 which means that for any darker brand colour, I would have to set gray-1 = #fff for the buttons to be legible, which would probably cause alot of other stuff to break

I mean you can modify the less variable, like:
```less
@btn-primary-color: #fff;
```

**Comment by akai** [comment]
> Now that I think about it, I'm not sure this UI change was intentional,
> ![image](https://user-images.githubusercontent.com/30278842/121083180-188b8b00-c7ad-11eb-8cae-09fd395de599.png)
> It seems than index.css has a syntax error (I get this message when I run "npm run build")

This seems to be a problem with the postcss plugin, see：https://github.com/facebook/create-react-app/discussions/10095

**Comment by MarcM0** [comment]
> > Now that I think about it, I'm not sure this UI change was intentional,
> > ![image](https://user-images.githubusercontent.com/30278842/121083180-188b8b00-c7ad-11eb-8cae-09fd395de599.png)
> > It seems than index.css has a syntax error (I get this message when I run "npm run build")
> 
> This seems to be a problem with the postcss plugin, see：[facebook/create-react-app#10095](https://github.com/facebook/create-react-app/discussions/10095)
> 
> or you can import less file:
> 
> ```js
> import '@chatui/core/es/styles/index.less';
> ```

the less file doesn't get rid of the error (and it can't replace index.css as far as I can tell). As for the postcss solutions, I don't think npm has an equivalent for resolutions.

**Comment by MarcM0** [comment]
just to be clear, I don't get this error in 0.3.3

**Comment by akai** [comment]
Can you show me the package.json file? the 0.3.3 and beta project

**Comment by MarcM0** [comment]
![image](https://user-images.githubusercontent.com/30278842/121917796-7404ce00-cd03-11eb-9e21-e605680fe1cb.png)

**Comment by akai** [comment]
v1.0.0-beta.5 has this line of code causing the error:

```
.ScrollView--fullWidth{margin:0 calc(var(--gutter)*-1)}
```

You can upgrade `postcss-custom-properties` to solve

```diff
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
+  },
+  "resolutions": {
+    "postcss-custom-properties": "^11.0.0"
+  },
+  "devDependencies": {
+    "postcss-custom-properties": "^11.0.0"
  }
```

and `npm i`

**Comment by MarcM0** [comment]
I still get the same error when I npm run build, I even tried npm ci

**Comment by akai** [comment]
I used create-react-app to build a new project. The same error occurred at the beginning, but after upgrading postcss-custom-properties, it worked. You can try to delete node_modules and try again

**Comment by akai** [comment]
or you can import the less file, by https://stackoverflow.com/questions/63386654/using-less-css-with-the-latest-create-react-app or https://dev.to/joefstack/how-to-setup-less-with-react-without-ejecting-1nej

**Comment by MarcM0** [comment]
I went with the less method, I also had to install less-plugin-import-node-modules to import from chatui.

**Comment by franva** [comment]
> ```diff
> postcss-custom-properties
> ```

Hi @akai What is the solution section in the package.json?
I searched and found it's just for `yarn`.
Do I have to use yarn to solve this issue?
