### ISSUE TITLE
Msg Scroll Direction

### ISSUE THREAD

**Issue by MarcM0** [alibaba/ChatUI#41]
**What problem does this feature solve? (这个功能解决了什么问题)**
Initially, messages start at the top and scroll to the bottom, and I need to change this direction

**Describe the solution you'd like (描述您想要的解决方案)**
I would like the option to change the direction messages come from
Before:
![1](https://user-images.githubusercontent.com/30278842/122463487-a7559000-cf83-11eb-89b9-95c2dd8f0568.JPG)
After:
![image](https://user-images.githubusercontent.com/30278842/122463524-b0466180-cf83-11eb-9477-9b5f8472c496.png)

**What does the proposed API look like?  (你期望的 API 是怎样的)**
Maybe an option in the chat object

**Comment by akai** [comment]
Sorry, don't plan to support
