### ISSUE TITLE
Less variables without less

### ISSUE THREAD

**Issue by MarcM0** [alibaba/ChatUI#45]
**What problem does this feature solve? (这个功能解决了什么问题)**
Using less requires major changes to many projects

**Describe the solution you'd like (描述您想要的解决方案)**
Ability to change the variables in var.less (at least btn-primary-color) without using less

**What does the proposed API look like?  (你期望的 API 是怎样的)**
maybe an option here? https://market.m.taobao.com/app/chatui/theme-builder/index.html

**Comment by akai** [comment]
You can override the style with css

```css
.Btn--primary {}
```

**Comment by MarcM0** [comment]
ah yes, I added 
`/* Change text colour in primary button */
.Btn--primary {
  color:var(--white)
}`
in the edit mode section of the site
