### ISSUE TITLE
[Bug] 接收消息时提示错误 TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by georgefeng** [alibaba/ChatUI#5]
此时后端已正常响应，并返回了消息内容，但错误提示如下：
![issue3](https://user-images.githubusercontent.com/23147020/95462831-9d1dd380-09aa-11eb-8975-5149abff4d33.PNG)

setup.js - ChatSDK - requests中的代码如下：
![issue2](https://user-images.githubusercontent.com/23147020/95463133-000f6a80-09ab-11eb-82ac-8c908ab4dcd3.PNG)

对应SDK中的报错位置如图：
![issue1](https://user-images.githubusercontent.com/23147020/95462706-71025280-09aa-11eb-9db0-9a5c1a3ea757.png)

**Comment by akai** [comment]
`requests.send` 请求后返回的数据是什么？

**Comment by georgefeng** [comment]
> `requests.send` 请求后返回的数据是什么？

{"type":"text","content":{"text":"my text"}}
![issue4](https://user-images.githubusercontent.com/23147020/95472819-0fe07c00-09b6-11eb-9ff9-22d63786dc61.PNG)

**Comment by akai** [comment]
需要返回数组格式 https://chatui.io/sdk/send，我们下个版本会做兼容

**Comment by akai** [comment]
你升级到 0.0.9 试一下，现在同时支持了

**Comment by georgefeng** [comment]
更新后已解决，谢谢
