### ISSUE TITLE
需要能够自定义发送按钮

### ISSUE THREAD

**Issue by locktongue** [alibaba/ChatUI#74]
**What problem does this feature solve? (这个功能解决了什么问题)**
需要自定义发送按钮的样式和内容（比如现在是纯文本，而之前可以是Icon）

**Describe the solution you'd like (描述您想要的解决方案)**
加一个prop，可以让我自定义发送按钮的组件

**What does the proposed API look like?  (你期望的 API 是怎样的)**
加个prop，只要能自定义组件并绑上默认点击事件啥的就行：

**Comment by akai** [comment]
你可以直接用 css 把样式改掉，或者直接给 `Chat` 组件传 prop `Composer`
