### ISSUE TITLE
Chat UI Pro Input框样式问题，  初始rows=3 而不是1

### ISSUE THREAD

**Issue by 3lou401** [alibaba/ChatUI#76]
**Version information (版本信息)**
- ChatUI or ChatUI Pro?
- ChatUI Version:
- React Version:
- OS Version:
- Browser Version:

**Describe the bug (描述问题)**

**Steps To Reproduce (重现步骤)**
1. 
2. 

**Link to minimal reproduction (最小化重现链接)**

**Expected behavior (期望的结果是什么)**

**Comment by akai** [comment]
是的，v0.2 在 PC 默认最小3行
