### ISSUE TITLE
sidebar 配置不显示

### ISSUE THREAD

**Issue by kiwilili** [alibaba/ChatUI#77]
ChatUI Pro
- ChatUI Version: 0.2.2
- React Version: 17
os: window10
- Browser Version: chrome 最新

**Describe the bug (描述问题)**
sidebar 配置不显示 使用 0.2.4 页面展示不出来 使用 0.2.2 不显示 sidebar

**Steps To Reproduce (重现步骤)**
1. config 增加 sidebar 配置

**Link to minimal reproduction (最小化重现链接)**
https://codesandbox.io/s/chatui-pro-x-react-forked-mchie?file=/src/App.js

**Expected behavior (期望的结果是什么)**
sidebar 可以展示出来

**Comment by akai** [comment]
配置在侧边栏里的卡片（code）需要自己注册，比如你现在配置的 `sidebar-suggestion` 等
