### ISSUE TITLE
brand 怎么自定义组件

### ISSUE THREAD

**Issue by kiwilili** [alibaba/ChatUI#79]
**Version information (版本信息)**sdk 0.2.2
- ChatUI or ChatUI Pro? ChatUI Pro
- ChatUI Version: 1.2.1
- React Version: 17.0.1
- OS Version:
- Browser Version: google laster

**Describe the bug (描述问题)** 
无法实现 brand 怎么自定义组件

**Steps To Reproduce (重现步骤)**
config: {
        navbar: {
          logo: 'https://gw.alicdn.com/tfs/TB1Wbldh7L0gK0jSZFxXXXWHVXa-168-33.svg',
          title: '来虎服务支持',
          code: 'brand-title', // 自定义组件不生效
        },
        ....
}

**Link to minimal reproduction (最小化重现链接)**
https://img.alicdn.com/imgextra/i2/O1CN01sA6Q5220fG0Us4WDj_!!6000000006876-2-tps-1584-1146.png
**Expected behavior (期望的结果是什么)**
navbar 如何自定义组件配置，实现如上图链接效果

**Comment by akai** [comment]
文档里有句话：

> 注：图中的 brand 和 sidebar 需要通过卡片来实现。

**Comment by kiwilili** [comment]
sidebar 我这边实现了 但是 brand 怎么配置卡片呢
{
    components: {
        'brand-title': Brand
    },
    config: {
       navbar: {
           code: 'brand-title', // 自定义组件不生效
       },
    }
}
也试了
config: {
   brand: {
       code: 'brand-title', // 自定义组件不生效
   },
}
以上都不生效

**Comment by akai** [comment]
```js
{
  config: {
    brand: { ... }, // 传配置
  },
  components: {
    header: MyHeader // 自定义的导航组件
  }
}
```

**Comment by 82kg** [comment]
> sidebar 我这边实现了 但是 brand 怎么配置卡片呢
> 
> ```
> {
>     components: {
>         'brand-title': Brand
>     },
>     config: {
>        navbar: {
>            code: 'brand-title', // 自定义组件不生效
>        },
>     }
> }
> ```
> 
> 也试了
> 
> ```
> config: {
>    brand: {
>        code: 'brand-title', // 自定义组件不生效
>    },
> }
> ```
> 
> 以上都不生效

请教 sidebar怎么实现的呀
