### ISSUE TITLE
Chat组件相册和表情功能是自带的吗？

### ISSUE THREAD

**Issue by jacktang** [alibaba/ChatUI#82]
网站demo截图如下

<img width="450" alt="截屏2021-12-25 下午11 43 20" src="https://user-images.githubusercontent.com/44341/147388685-3be3c590-2542-494b-a20d-0754f98c0697.png">

在没有使用pro的情况下，如果要相册和表情功能要怎么配置？
已经尝试过 `type=image` 或者 `type=emoji`

**Comment by akai** [comment]
不是，需要自己写逻辑
