### ISSUE TITLE
Chat组件添加toolbar后，图标不出现是那个样式没引入吗？

### ISSUE THREAD

**Issue by jacktang** [alibaba/ChatUI#83]
添加toolbar后按钮图标没出现

<img width="848" alt="截屏2021-12-25 下午11 43 45" src="https://user-images.githubusercontent.com/44341/147388737-c44c7121-20ee-47cb-96a0-e2dfaadc2114.png">

目前已经引入的样式是

```
import '@chatui/core/es/styles/index.less';
import '@chatui/core/dist/index.css';
```

**Comment by jacktang** [comment]
原因找到了，是因为没有引入svg。这个图标是自己可以换的吗？如果可以，怎么换呢？

**Comment by akai** [comment]
你对照着 svg symbol id 替换就行了

**Comment by hellohongfu36233** [comment]
> 原因找到了，是因为没有引入svg。这个图标是自己可以换的吗？如果可以，怎么换呢？

如何添加SVG？我也遇到了同样的问题

![image](https://github.com/alibaba/ChatUI/assets/152071661/9c26eeca-2e6a-48c6-a5cb-adeddeb4f481)

**Comment by neilzhengzx** [comment]
demo中的代码: <script src="//g.alicdn.com/chatui/icons/2.6.2/index.js" async></script>
