### ISSUE TITLE
Prevent scroll to bottom when not on bottom

### ISSUE THREAD

**Issue by ScreamZ** [alibaba/ChatUI#96]
Hello, thanks for this awesome library that gives much inspiration! (even if not documented in English ahah)

I would like to prevent the default behavior where the screen scroll down on a new message with something like this: https://github.com/compulim/react-scroll-to-bottom

scroll to bottom only if we already are on the bottom.
This allows the user to to being auto-jumped if he is searching in some sort of history and a new message come.

Is it already possible ?

Thanks

**Comment by akai** [comment]
It's supported back to the bottom
