### ISSUE TITLE
这项目是不是死在这了，pro的文档也是极简，还不支持npm第三方包下载

### ISSUE THREAD

**Issue by huanlirui** [alibaba/ChatUI#98]
![image](https://user-images.githubusercontent.com/40491203/204189380-6e68b05e-b9a8-4654-9fb3-7686d6462a09.png)
随便copy下组件代码，都是在报错。

**Comment by huanlirui** [comment]
![image](https://user-images.githubusercontent.com/40491203/204191848-d77a9683-9f51-480a-8542-aaa6f4849481.png)
api类型文档也没有？

**Comment by akai** [comment]
升级到 v2.4.8-beta.0 试试
