### ISSUE TITLE
是否打算开源并提供NPM形式安装Pro?

### ISSUE THREAD

**Issue by davidliudev** [alibaba/ChatUI#99]
目前虽然Pro的SDK是不错的可以用的，但是没法再更精细的进行定制化。
另外因为内部代码审查的机制，非开源的产品内部是无法通过安全审查的。

所以还是问一下是否打算开源Pro的部分，哪怕是开源收费模式也没关系

后面团队内部好继续决定是否重复造个轮子

**Comment by xuchen** [comment]
同问！

**Comment by akai** [comment]
pro 暂不开源
